name: Update App Source Language File

on:
  push:
    branches: ["main"]
    paths:
      - "app.py"
      - "package_build/*.py"
      - "pyproject.toml"
      - ".github/workflows/update-source-language-file.yml"

  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install Poethepoet
        run: pipx install poethepoet

      - name: Install gettext utils
        run: sudo apt install gettext

      - name: Extract localizable strings
        run: |
          poe xgettext
          python3 ci-scripts/no_pot_creation_date.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update source language file
          commit-message: Update source language file
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          add-paths: package_build/locale/messages.pot
          delete-branch: true
